version: '3'
services: 
    app: 
        container_name: docker-docx-au
        restart: always
        build: .
        ports: 
            - '80:8000'
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'